### ISSUE TITLE
Add a flag or setting to output to Comfy's output folder

### ISSUE THREAD

**Issue by tigerAspect** [Jordach/CAPGUI#1]
Either a startup flag or config or setting that lets me just dump everything run into a folder, especially with how fragile Gradio is on mobile to loss of focus, a backup option of it just getting spat out into the output folder would be great.

**Comment by Jordach** [comment]
Fixed with https://github.com/Jordach/CAPGUI/commit/5db43fef61331f81f2563303a6d4711c9b473f13.
